var element;
element = document;
console.log(element);
var elements;
elements = document.head;
console.log(elements);
var elemnt;
elemnt = document.links;
console.log(elemnt);
var elemnat;
document.getElementsByClassName("header").innerHTML = "<h1>hello world</h1>";
elemnat = document.getElementsByClassName("header").innerHTML;
console.log(elemnat);
var elemants;
document.getElementsByClassName("box").setAttributes("class","abc");
elemants = document.getElementsByClassName("box").getAttributes("class");
console.log(elemants);